"""Entropy Visualizer

Loads a simulated grid of (O, T_visible, S, E_index) and produces
simple visualizations (line plots or heatmaps) for inspection.

Example:
    python entropy_visualizer.py --csv data/simulated_grid.csv --mode heatmap

Note:
    - Requires matplotlib and numpy.
"""

import argparse
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import csv


def load_grid(csv_path: Path):
    t_vals = []
    s_vals = []
    e_vals = []

    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            t_vals.append(float(row["T_visible"]))
            s_vals.append(float(row["S"]))
            e_vals.append(float(row["E_index"]))

    t_vals = np.array(t_vals)
    s_vals = np.array(s_vals)
    e_vals = np.array(e_vals)

    # Infer unique grid
    t_unique = np.unique(t_vals)
    s_unique = np.unique(s_vals)

    T, S = np.meshgrid(t_unique, s_unique)
    E = e_vals.reshape(len(s_unique), len(t_unique))
    return T, S, E


def plot_heatmap(T, S, E, out_path: Path):
    plt.figure()
    plt.imshow(E, origin="lower",
               extent=[T.min(), T.max(), S.min(), S.max()],
               aspect="auto")
    plt.colorbar(label="E_index")
    plt.xlabel("T_visible")
    plt.ylabel("S (entropy index)")
    plt.title("Efficiency Index Heatmap (E_index)")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=160, bbox_inches="tight")
    print(f"Saved heatmap to {out_path.resolve()}")


def plot_time_slice(T, S, E, out_path: Path):
    # Take middle S row for a time-slice
    mid_idx = E.shape[0] // 2
    t_line = T[mid_idx, :]
    e_line = E[mid_idx, :]

    plt.figure()
    plt.plot(t_line, e_line)
    plt.xlabel("T_visible")
    plt.ylabel("E_index")
    plt.title(f"E_index vs T_visible (S ≈ {S[mid_idx, 0]:.2f})")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=160, bbox_inches="tight")
    print(f"Saved time-slice plot to {out_path.resolve()}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Visualize entropy/efficiency surfaces.")
    parser.add_argument("--csv", type=str, default="data/simulated_grid.csv",
                        help="CSV file generated by efficiency_simulator.py")
    parser.add_argument("--mode", type=str, default="heatmap",
                        choices=["heatmap", "time_slice"],
                        help="Type of plot to generate.")
    parser.add_argument("--out", type=str, default="diagrams/efficiency_heatmap.png",
                        help="Output image path.")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    T, S, E = load_grid(csv_path)
    out_path = Path(args.out)

    if args.mode == "heatmap":
        plot_heatmap(T, S, E, out_path)
    else:
        plot_time_slice(T, S, E, out_path)


if __name__ == "__main__":
    main()
